services:
  task-api-db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=D7uli0o71H
      - POSTGRESQL_DATABASE=mvp_db

  task-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9080:9080
    env_file:
      - ./.env
    depends_on:
      - task-api-db
