/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Flash Tasks API
 * OpenAPI spec version: 1.4.1
 */
import type {
  HealthCheck200
} from '../api.schemas'

/**
 * Health check
 */
export type healthCheckResponse = {
  data: HealthCheck200;
  status: number;
  headers: Headers;
}

export const getHealthCheckUrl = () => {


  return `http://mvp-ecs-alb-97805771.us-east-1.elb.amazonaws.com:3000/metrics/health`
}

export const healthCheck = async ( options?: RequestInit): Promise<healthCheckResponse> => {
  
  const res = await fetch(getHealthCheckUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }

  )
  const data = await res.json()

  return { status: res.status, data, headers: res.headers }
}


