name: Run Integration Tests

on:
  workflow_call:

jobs:
  integration-tests:
    name: Integration
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: 'services/api'

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          POSTGRESQL_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRESQL_DATABASE: ${{ vars.DATABASE_NAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: npm
          cache-dependency-path: 'services/api/package-lock.json'
      
      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npx prisma migrate deploy
        env: 
            DATABASE_URL: "postgresql://${{ secrets.DATABASE_USERNAME }}:${{ secrets.DATABASE_PASSWORD }}@localhost:5432/${{ vars.DATABASE_NAME }}?schema=public"
      
      - name: Run integration tests
        run: npm run test:integration
        env: 
            DATABASE_URL: "postgresql://${{ secrets.DATABASE_USERNAME }}:${{ secrets.DATABASE_PASSWORD }}@localhost:5432/${{ vars.DATABASE_NAME }}?schema=public"
