name: Run Integration Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  integration-tests:
    name: Integration Tests E2E
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: 'services/api'
    strategy:
      matrix:
        node-version: [20.18.1]

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          POSTGRESQL_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRESQL_DATABASE: ${{ vars.DATABASE_NAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: 'services/api/package-lock.json'
      
      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npx prisma migrate deploy
        env: 
            DATABASE_URL: "postgresql://${{ secrets.DATABASE_USERNAME }}:${{ secrets.DATABASE_PASSWORD }}@localhost:5432/${{ vars.DATABASE_NAME }}?schema=public"
      
      - name: Run integration tests
        run: npm run test:integration
