name: Run Integration Tests

on:
  workflow_call:

jobs:
  backend-build:
    name: Build API
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: 'services/api'
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: npm
          cache-dependency-path: 'services/api/package-lock.json'
      
      - name: Install dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-build
          path: ./build
