name: Run Integration Tests

on:
  workflow_call:

jobs:
  backend-build:
    name: Build API
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: 'services/api'
    strategy:
      matrix:
        node-version: [20.18.1]
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: 'services/api/package-lock.json'
      
      - name: Install dependencies
        run: npm ci

      - name: Build Package
        run: npm run build
